## 01. 머신러닝과 딥러닝 

### 1.1 인공지능, 머신 러닝과 딥러닝 

인공지능은 인간의 지능을 모방하여 사람이 하는 일을 컴퓨터가 할 수 있도록 하는 기술이다. 
- 인공지능 구현 방법으로는 머신 러닝과 딥 러닝이 있다. 

머신러닝 
- 주어진 데이터를 인간이 먼저 처리한다. 
- 범용적인 목적을 위해 제작된 것으로 데이터의 특징을 스스로 추출하지 못한다. 

딥러닝 
- 인간이 하던 작업을 생략한다
- 대량의 데이터를 신경망에 적용하며 컴퓨터가 스스로 분석한 후 답을 찾는다


### 1.2 머신 러닝이란

#### 1.2.1 머신 러닝 학습 과정 
- 학습 단계와 예측 단계로 구분할 수 있다. 
- 훈련 데이털르 머신 러닝 알고리즘에 적용해 학습하고 이 결과로 모형이 생성된다. 

주요 구성요소 : 데이터와 모델(모형)

#### 1.2.2 머신 러닝 학습 알고리즘 
머신 러닝의 학습 알고리즘 : 지도 학습, 비지도 학습, 강화 학습 

1. 지도학습 : 정답이 무엇인지 컴퓨터에게 알려 주고 학습시키는 방법 
2. 비지도학습 : 정답을 알려주지 않고 특징이 비슷한 데이터를 클러스터링하여 예측하는 방법 
3. 강화학습 : 분류할 수 있는 데이터가 있는 것도 아니고 데이터가 있다고 해도 정답이 없기 때문

### 1.3 딥러닝이란 
딥러닝은 인간의 신경망 원리를 모방한 심층 신경망 이론을기반으로 고안된 머신 러닝 방법의 일종이다.

#### 1.3.1 딥러닝 학습 과정 
1. 데이터 준비
2. 모델 정의 
3. 모델 컴파일
4. 모델 훈련 
5. 모델 예측 

#### 1.3.2 딥러닝 학습 알고리즘 
- 지도학습 
    - 합성곱 신경망 (CNN): 목적에 따라 이미지 분류, 인식, 분할로 분류할 수 있다. 
    - 순환 신경망 (RNN) : 시계열 데이터 분류 시 이용 

- 비지도 학습 
    - 워드 임베딩 
    - 군집 : 아무런 정보가 없는 상태에서 데이터를 분류하는 방법 

- 전이 학습 : 사전에 학습이완료된 모델을 가지고 우리가 원하는 학습에 미세 조정 기법을 이용하여 학습시키는 방법이다 

- 사전 학습 모델 : 풀고자 하는 문제와 비슷하면서 많은 데이터로 이미 학습이 되어 있는 모델이다. 

# 02. 실습 환경 설정과 파이토치 기초 

### 2.1 파이토치 개요 

#### 2.1.1 파이토치 특징 및 장점 
특징 : GPU에서 텐서 조작 및 동적 신경망 구축이 가능한 프레임워크 

- GPU : 연산 속도를 빠르게 하는 역할 
- 텐서 : 파이토치에서는 데이터 형태이며 단일 데이터 형식으로 된 자료들의 다차원 행렬이다 
- 동적 신경망 : 훈련을 반복할 때마다 네트워크 변경이 가능한 신경망을 의미 

In [10]:
import torch

print(torch.tensor([[1,2], [3,4]]))
print(torch.tensor([[1,2], [3,4]], device="cpu"))
print(torch.tensor([[1,2], [3,4]], dtype=torch.float64))

tensor([[1, 2],
        [3, 4]])
tensor([[1, 2],
        [3, 4]])
tensor([[1., 2.],
        [3., 4.]], dtype=torch.float64)


In [11]:
#텐서를 ndarray로 변환
temp = torch.tensor([[1,2], [3,4]])
print(temp.numpy())

temp = torch.tensor([[1,2], [3,4]], device="cpu")
print(temp.to("cpu").numpy())

[[1 2]
 [3 4]]
[[1 2]
 [3 4]]


In [12]:

temp = torch.FloatTensor([1, 2, 3, 4, 5, 6, 7])
print(temp[0], temp[1], temp[-1])
print('------------------------')
print(temp[2:5], temp[4:-1])

tensor(1.) tensor(2.) tensor(7.)
------------------------
tensor([3., 4., 5.]) tensor([5., 6.])


In [13]:
v = torch.tensor([1, 2, 3])
w = torch.tensor([3, 4, 6])
print(w - v)

tensor([2, 2, 3])


In [14]:
#차원 조작
temp = torch.tensor([
    [1,2], [3,4]])

print(temp.shape)
print('------------------------')
print(temp.view(4, 1))
print('------------------------')
print(temp.view(-1))
print('------------------------')
print(temp.view(1, -1))
print('------------------------')
print(temp.view(-1, 1))

torch.Size([2, 2])
------------------------
tensor([[1],
        [2],
        [3],
        [4]])
------------------------
tensor([1, 2, 3, 4])
------------------------
tensor([[1, 2, 3, 4]])
------------------------
tensor([[1],
        [2],
        [3],
        [4]])


In [15]:
#import pandas as pd
#import torch
#data = pd.read_csv('../class2.csv')

#x = torch.from_numpy(data['x'].values).unsqueeze(dim=1).float()
#y = torch.from_numpy(data['y'].values).unsqueeze(dim=1).float()
     

In [16]:
#import pandas as pd
#import torch
#from torch.utils.data import Dataset
#from torch.utils.data import DataLoader

#class CustomDataset(Dataset):
  #def __init__(self, csv_file):
    #self.label = pd.read_csv(csv_file)
  #def __len__(self):
    #return len(self.label)
  #def __getitem__(self, idx):
    #sample = torch.tensor(self.label.iloc[idx,0:3]).int()
    #label = torch.tensor(self.label.iloc[idx,3]).int()
    #return sample, label

#tensor_dataset = CustomDataset('../covtype.csv')
#dataset = DataLoader(tensor_dataset, batch_size=4, shuffle=True)

In [17]:
#!pip install requests

In [18]:
#import torchvision.transforms as transforms

#mnist_transform = transforms.Compose([
    #transforms.ToTensor(),
    #transforms.Normalize((0.5,), (1.0,))
#])

#from torchvision.datasets import MNIST
#import requests
#download_root = '../chap02/data/MNIST_DATASET'

#train_dataset = MNIST(download_root, transform=mnist_transform, train=True,
                      #download=True)
#valid_dataset = MNIST(download_root, transform=mnist_transform, train=False,
                      #download=True)
#test_dataset = MNIST(download_root, transform=mnist_transform, train=False,
                     #download=True)
     

In [19]:
#model = nn.linear(in_features=1, out_features=1, bias=True)
     

In [20]:
#class MLP(Module):
  #def __init__(self, inputs):
    #super(MLP, self).__init__()
    #self.layer = nn.Linear(inputs, 1)
  #def forward(self, X):
    #X = self.layer(X)
    #X = self.activation
    #return X

In [21]:
import torch.nn as nn
class MLP(nn.Module):
  def __init__(self):
    super(MLP, self).__init__()
    self.layer1 = nn.Sequential(
        nn.Conv2d(in_channels=3, out_channels=64, kernel_size=5),
        nn.ReLU(inplace=True),
        nn.MaxPool2d(2))

    self.layer2 = nn.Sequential(
        nn.Conv2d(in_channels=64, out_channels=30, kernel_size=5),
        nn.ReLU(inplace=True),
        nn.MaxPool2d(2))

    self.layer3 = nn.Sequential(
        nn.Linear(in_features=30*5*5, out_features=10, bias=True),
        nn.ReLU(inplace=True))


    def forward(self, x):
      x = self.layer1(x)
      x = self.layer2(x)
      x = x.view(x.shape[0], -1)
      x = self.layer3(x)
      return x
model = MLP()

print("Printing children\n------------------------------")
print(list(model.children()))
print("\n\nPrinting Modules\n------------------------------")
print(list(model.modules()))

Printing children
------------------------------
[Sequential(
  (0): Conv2d(3, 64, kernel_size=(5, 5), stride=(1, 1))
  (1): ReLU(inplace=True)
  (2): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
), Sequential(
  (0): Conv2d(64, 30, kernel_size=(5, 5), stride=(1, 1))
  (1): ReLU(inplace=True)
  (2): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
), Sequential(
  (0): Linear(in_features=750, out_features=10, bias=True)
  (1): ReLU(inplace=True)
)]


Printing Modules
------------------------------
[MLP(
  (layer1): Sequential(
    (0): Conv2d(3, 64, kernel_size=(5, 5), stride=(1, 1))
    (1): ReLU(inplace=True)
    (2): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
  )
  (layer2): Sequential(
    (0): Conv2d(64, 30, kernel_size=(5, 5), stride=(1, 1))
    (1): ReLU(inplace=True)
    (2): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
  )
  (layer3): Sequential(
    (0): Linea

In [22]:
def MLP(in_features=1, hidden_features=20, out_features=1):
  hidden = nn.Linear(in_features=in_features, out_features=hidden_features,
                     bias=True)
  activation = nn.ReLU()
  output = nn.Linear(input_features=hidden_features, out_features=out_features,
                     bias=True)
  net = nn.Sequential(hidden, activation, output)
  return net
     

In [23]:
#모델의 파라미터 정의
#from torch.optim import optimizer
#criterion = torch.nn.MSELoss()
#optimizer = torch.optim.SGD(model.parameters(), lr=0.01, momentum=0.9)
#scheduler = torch.optim.lr_scheduler.LambdaLR(optimizer=optimizer,
                                              #lr_lambda=lambda epoch: 0.95 ** epoch)
#for epoch in range(1, 100+1):
  #for x, y in dataloader:
    #optimizer.zero_grad()
#loss_fn(model(x), y).backward()
#optimizer.step()
#scheduler.step()

In [24]:
#for epoch in range(100):
  #yhat = model(x_train)
  #loss = criterion(yhat, y_train)
  #optimizer.zero_grad()
  #loss.backward()
  #optimizer.step()

In [25]:
!pip install torchmetrics

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 983.4/983.4 kB 28.5 MB/s  0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2/2 [torchmetrics] [torchmetrics]

[notice] A new release of pip is available: 26.1.2 -> 26.2.1
[notice] To update, run: pip install --upgrade pip


In [26]:
import torch
import torchmetrics

preds = torch.randn(10, 5).softmax(dim=-1)
target = torch.randint(5, (10,))

acc = torchmetrics.functional.accuracy(preds, target, task='multiclass', num_classes=5)

In [27]:
#모듈을 이용한 모델 평가
import torch
import torchmetrics
metric = torchmetrics.Accuracy(task='multiclass', num_classes=5)

n_batches = 10
for i in range(n_batches):
  preds = torch.randn(10, 5).softmax(dim=-1)
  target = torch.randint(5, (10,))

  acc = metric(preds, target)
  print(f"Accuracy on batch {i}: {acc}")

acc = metric.compute()
print(f"Accuracy on all data: {acc}")

Accuracy on batch 0: 0.5
Accuracy on batch 1: 0.5
Accuracy on batch 2: 0.30000001192092896
Accuracy on batch 3: 0.0
Accuracy on batch 4: 0.0
Accuracy on batch 5: 0.10000000149011612
Accuracy on batch 6: 0.4000000059604645
Accuracy on batch 7: 0.5
Accuracy on batch 8: 0.20000000298023224
Accuracy on batch 9: 0.30000001192092896
Accuracy on all data: 0.2800000011920929


In [28]:
#!pip install tensorboard

In [29]:
#import torch
#from torch.utils.tensorboard import SummaryWriter
#writer = SummaryWriter("../chap02/tensorboard")

#for epoch in range(num_epochs):
  #model.train()
  #batch_loss = 0.0

  #for i (x, y) in enumerate(dataloader):
    #x, y = x.to(device).float(), y.to(device).float()
    #outputs = model(x)
    #loss = criterion(outputs, y)
    #writer.add_scalar("Loss", loss, epoch)
    #optimizer.zero_grad()
    #loss.backward()
    #optimizer.step()

#writer.close()

In [30]:
#tensorboard --logdir=../chap02/tensorboard --port=6006